#:schema node_modules/wrangler/config-schema.json
name = "bokimaru-next-lp"
compatibility_date = "2026-06-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "bokimaru-reviews"
database_id = "ecb72992-54fe-4cc8-af1b-49615381691f"
